language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
    - nasm
sudo: false
install:
  - pip install -U setuptools pip
  - pip install -U py pytest
  - pip install --no-binary capstone,keystone-engine -e .[asm,disasm,rop,ssh]
script:
  - WANT_KEYSTONE=0 python setup.py test
